[package]
name = "mos_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = {"version" = "1.4.0", "features" = ["spin_no_std"]}
spin = {"version" = "0.9.8"}
buddy_system_allocator = "0.9.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
