[build]
target = "mipsel-unknown-none"
rustflags = ["-Clink-args=-EL -Tsrc/kernel.lds -G 0 -static", "-Clink-dead-code=yes", "-Clinker=mips-linux-gnu-ld", "-g"]
[unstable]
build-std = ["core", "alloc"]